AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{cookiecutter.service_name}}

  {{cookiecutter.service_description}}

Parameters:
  Environment:
    Type: String
    Description: "Name of deployment environment"


Resources:


Outputs:
  AppUrl:
    Description: "Application URL"
    Value: <<VALUE>>
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-AppUrl"

